messageCF = "Inserire codice fiscale: "
messageError = "Input non valido"
messageN = "Inserire nome: "
messageC = "Inserire cognome"
choice1 = "Registrazione"
choice2 = "Prelievo Farmaci"
initialMessage = "Benvenuto \n questo è un sistema per la gestione dei farmaci attraverso comandi vocali. \n" \
                 "Puoi scegliere di disattivarmi quando vuoi, basta dire Stop. \n Ricorda di parlare dopo il bip. \n" \
                 "Che operazione desidéri svolgere?"
messageAfterStop = "Da ora in avanti non ti guiderò, ma puoi sempre riattivarmi dicendo Start"
messageWelcome = "Benvenuto\n Che operazione desideri svolgere?"
messagePhoto = "Adesso il sistema verificherà se sei un utente reale. \n Quando apparirà un quadrato verde intorno al" \
               "tuo viso, premi Q per scattare una foto. "
numberMedicines = "Quanti farmaci assumi?"
numberDelegate = "A chi vuoi delegare il prelievo di farmaci?"
enrollmentCompleted = "REGISTRAZIONE COMPLETATA!"
recognitionRejected = "UTENTE NON RICONOSCIUTO"
messageRecognition = "Chi sei?"
recognitionChoice1 = "Paziente"
recognitionChoice2 = "Delegato"
spoofingMessage = "ANTISPOOFING ERROR!\n L'UTENTE NON SEMBRA ESSERE REALE!"
messageMedicine = "Inserisci nome farmaco"
messageDelegateError = "Inserisci i codici fiscali corretti dei tuoi delegati"
errorSpeechRec = "Non ho capito, puoi ripetere?"
errorSpelling = "Puoi farmi lo spelling?"
confirmCF = "Il tuo codice fiscale"
errorFirstName = "Il tuo nome è "
errorLastName = "Il tuo cognome è "
confirm = "Confermi?"
medicineConfirm = "Confermi che il medicinale inserito è"
numberMedicinesConfirm = "Confermi che il numero dei medicinali da inserire è"
medConfirm = "Sono questi i medicinali che vuoi registrare?"
changeMed = "Qual è il farmaco che vorresti correggere?"
otherMedToChange = "Ci sono altri farmaci che vuoi correggere?"
errorIndexMedicine = "Numero errato"
dosageMedicine = "Qual è il dosaggio del farmaco?"
yes = "Sì"
no = "No"
